/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pwhhmvegaslnsbpqbyac"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3aGhtdmVnYXNsbnNicHFieWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NDY2NjQsImV4cCI6MjA3ODEyMjY2NH0.PG-OSNqU8X21DOS73MlVXG-G4wHoP9U7WtHn_aaU0Cs"